# matugen colors (loaded first, overridden below)
include ~/.cache/matugen/kitty-colors.conf

# font
font_family JetBrainsMono Nerd Font
font_size 12

# looks
background_opacity 0.5
window_padding_width 1 4

# cursor
cursor_blink_interval 0.5
cursor_stop_blinking_after 1

# scroll
wheel_scroll_min_lines 1

# remote control
allow_remote_control yes
listen_on unix:/tmp/kitty-$KITTY_PID

# close without confirm
confirm_os_window_close 0

# Enable the cursor trail
cursor_trail 3

# Adjust the decay time (how long the trail lasts in seconds)
cursor_trail_decay 0.1 0.4

# Adjust the distance threshold (minimum pixels moved to trigger trail)
cursor_trail_start_threshold 2
