# matugen colors (loaded first, overridden below)
include ~/.config/kitty/kitty-colors.conf

# font
font_family JetBrainsMono Nerd Font
font_size 12

# looks
background_opacity 0.4
window_padding_width 2

# cursor
cursor_blink_interval 0.5
cursor_stop_blinking_after 1

# scroll
wheel_scroll_min_lines 1

# clipboard
map ctrl+insert paste_from_clipboard

# remote control
allow_remote_control yes

# close without confirm
confirm_os_window_close 0
