# matugen colors for kitty
color0  #1c1f27
color1  #ffb4ab
color2  #2a619e
color3  #bcc7db
color4  #a4c9fe
color5  #543f5e
color6  #657895
color7  #e1e2e9
color8  #43474e
color9  #ffe2de
color10 #d9bde3
color11 #dde3ed
color12 #d6e7ff
color13 #6f537d 
color14 #3c4758
color15 #e1e2e9
cursor  #a4c9fe
selection_background #1f4876
url_color #1f4876
