# matugen colors for kitty
color0  #192225
color1  #ffb4ab
color2  #00798f
color3  #b2cbd2
color4  #84d2e6
color5  #3e4565
color6  #5b848e
color7  #dee3e5
color8  #3f484b
color9  #ffe2de
color10 #bec5eb
color11 #d2e1e5
color12 #aee2ef
color13 #515b85 
color14 #334a50
color15 #dee3e5
cursor  #84d2e6
selection_background #004e5c
url_color #004e5c
