# matugen colors for kitty
# Standard ANSI Colors (0-7)
color0  #111318             # Black/Background
color1  #ffb4ab               # Red
color2  #2b609e # Green
color3  #bcc7db           # Yellow
color4  #a5c9fe             # Blue
color5  #543f5e   # Magenta
color6  #677894 # Cyan
color7  #aaccfe           # White/Foreground

# Bright ANSI Colors (8-15)
color8  #43474e      # Bright Black (Gray)
color9  #ffe2de # Bright Red
color10 #3679c6            # Bright Green
color11 #dde3ed # Bright Yellow
color12 #bed8fe # Bright Blue
color13 #6f537d # Bright Magenta
color14 #8492aa # Bright Cyan
color15 #e1e2e9        # Bright White

# UI Elements
cursor               #677894
selection_background #75859f
url_color            #204876