words = [
    "autocmd",
    "autocmds",
    "autofetch",
    "autotag",
    "Avante",
    "awww",
    "bashls",
    "binde",
    "bindel",
    "bindl",
    "bindm",
    "brightnessctl",
    "btop",
    "bufferline",
    "calcurse",
    "capslock",
    "catppuccin",
    "checkhealth",
    "clipse",
    "Cmdline",
    "codelldb",
    "combi",
    "Condit",
    "cssls",
    "ddcutil",
    "debugpy",
    "dmenu",
    "dotglob",
    "dpms",
    "drun",
    "dunst",
    "dunstctl",
    "dunstrc",
    "ellisonleao",
    "folke",
    "gapsin",
    "gapsout",
    "getchar",
    "gifs",
    "gitsigns",
    "grug",
    "gsettings",
    "Gunaratna",
    "gvfs",
    "halign",
    "hipatterns",
    "hrsh",
    "hypr",
    "hyprctl",
    "hyprlock",
    "hyprshot",
    "Hyprsunset",
    "jsonls",
    "keybinds",
    "keymap",
    "kwalletrc",
    "lazydev",
    "lazypath",
    "lazyrepo",
    "lazyvim",
    "libadwaita",
    "localsend",
    "lspconfig",
    "lspinfo",
    "magick",
    "matugen",
    "mousescroll",
    "movefocus",
    "movetoworkspace",
    "movewindow",
    "mpvpaper",
    "msword",
    "neoconf",
    "neodev",
    "noautomute",
    "Noice",
    "nvim",
    "officedocument",
    "onlyoffice",
    "openxmlformats",
    "pkill",
    "playerctl",
    "Pmenu",
    "Popupmenu",
    "poweroff",
    "presentationml",
    "ptop",
    "pulseaudio",
    "rasi",
    "resizewindow",
    "rgba",
    "rofi",
    "RRGGBB",
    "RRGGBBAA",
    "RTMIN",
    "rustaceanvim",
    "Sbar",
    "Senal",
    "setsid",
    "setvcp",
    "shellcheck",
    "shfmt",
    "shopt",
    "sigusr",
    "spreadsheetml",
    "stdpath",
    "stylesheet",
    "subfolders",
    "swapwindow",
    "swww",
    "taplo",
    "termguicolors",
    "textobjects",
    "togglespecialworkspace",
    "tohtml",
    "tokyonight",
    "Trunc",
    "undercurl",
    "uwsm",
    "venv",
    "vtsls",
    "wallpaperengine",
    "wayapper",
    "waybar",
    "waypaper",
    "webp",
    "williamboman",
    "winblend",
    "windowrule",
    "wiremix",
    "wordprocessingml",
    "wpctl",
    "xsettingsd",
    "xwayland",
    "yanky",
    "yazi",
    "zindex",
]