[mgr]
prepend_keymap = [
  # gvfs mount plugin
  { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount", desc = "Select device then mount" },
  { on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
  { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount", desc = "Select device then unmount" },
  { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
  # { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Select device then force to eject/unmount" },
  { on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
  { on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
  { on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "Automount then select device to jump to its mount point" },
  { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },
  { on = [ "M", "t" ], run = "plugin gvfs -- automount-when-cd", desc = "Enable automount when cd to device under cwd" },
  { on = [ "M", "T" ], run = "plugin gvfs -- automount-when-cd --disabled", desc = "Disable automount when cd to device under cwd" },

  # Recycle Bin Actions
  { on = ["R","b"], run = "plugin recycle-bin --launch",    desc = "Open Recycle Bin menu" },
  { on = ["R","o"], run = "plugin recycle-bin --open",      desc = "Open Trash" },
  { on = ["R","e"], run = "plugin recycle-bin --empty",     desc = "Empty Trash" },
  { on = ["R","D"], run = "plugin recycle-bin --emptyDays", desc = "Empty by days deleted" },
  { on = ["R","d"], run = "plugin recycle-bin --delete",    desc = "Delete from Trash" },
  { on = ["R","r"], run = "plugin recycle-bin --restore",   desc = "Restore from Trash" },

  # Open terminal
  { on = "<C-t>", run = 'shell "kitty --detach"', desc = "Open terminal here" },

  # Compression Selection Menu (c -> c)
  { on = ["c", "c", "1"], run = "plugin ouch tar.gz", desc = "Compress with ouch (.tar.gz)" },
  { on = ["c", "c", "2"], run = "plugin ouch zip",    desc = "Compress with ouch (.zip)" },
  { on = ["c", "c", "3"], run = "plugin ouch 7z",     desc = "Compress with ouch (.7z)" },

  # Interactive compress dialog
  { on = ["c", "o"], run = "plugin ouch", desc = "Compress with ouch" },

  # Extraction
  { on = ["c", "x"], run = 'shell "ouch d -y %s" --confirm', desc = "Extract with ouch" },
]
