[mgr]
prepend_keymap = [
  # Mount Plugin
  { on = ["M", "m",], run = "plugin mount", desc = "Open mount manager" },

  # gvfs mount plugin
  { on = ["M", "m",], run = "plugin mount", desc = "Open mount manager" },
  { on = [ "M", "m", "g" ], run = "plugin gvfs -- select-then-mount --jump", desc = "GVFS: select device to mount and jump" },
  { on = [ "M", "m", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "GVFS: select device then eject" },
  { on = [ "M", "m", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "GVFS: remount device under cwd" },
  { on = [ "M", "m", "a" ], run = "plugin gvfs -- add-mount", desc = "GVFS: add a mount URI" },
  { on = [ "M", "m", "e" ], run = "plugin gvfs -- edit-mount", desc = "GVFS: edit a mount URI" },
  { on = [ "M", "m", "r" ], run = "plugin gvfs -- remove-mount", desc = "GVFS: remove a mount URI" },
  { on = [ "M", "m", "j" ], run = "plugin gvfs -- jump-to-device --automount", desc = "GVFS: automount then jump to device" },
  { on = [ "M", "m", "b" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "GVFS: jump back to previous cwd" },
  { on = [ "M", "m", "t" ], run = "plugin gvfs -- automount-when-cd", desc = "GVFS: enable automount when cd to device" },
  { on = [ "M", "m", "T" ], run = "plugin gvfs -- automount-when-cd --disabled", desc = "GVFS: disable automount when cd to device" },

  # Recycle Bin Actions
  { on = ["R","b"], run = "plugin recycle-bin --launch",    desc = "Open Recycle Bin menu" },
  { on = ["R","o"], run = "plugin recycle-bin --open",      desc = "Open Trash" },
  { on = ["R","e"], run = "plugin recycle-bin --empty",     desc = "Empty Trash" },
  { on = ["R","D"], run = "plugin recycle-bin --emptyDays", desc = "Empty by days deleted" },
  { on = ["R","d"], run = "plugin recycle-bin --delete",    desc = "Delete from Trash" },
  { on = ["R","r"], run = "plugin recycle-bin --restore",   desc = "Restore from Trash" },

  # Open terminal
  { on = "<C-t>", run = 'shell "kitty --detach"', desc = "Open terminal here" },

  # Compression Selection Menu (c -> c)
  { on = ["c", "c", "1"], run = "plugin ouch tar.gz", desc = "Compress with ouch (.tar.gz)" },
  { on = ["c", "c", "2"], run = "plugin ouch zip",    desc = "Compress with ouch (.zip)" },
  { on = ["c", "c", "3"], run = "plugin ouch 7z",     desc = "Compress with ouch (.7z)" },

  # Interactive compress dialog
  { on = ["c", "o"], run = "plugin ouch", desc = "Compress with ouch" },

  # Extraction
  { on = ["c", "x"], run = 'shell "ouch d -y %s" --confirm', desc = "Extract with ouch" },
]
