[config]
mode = "dark"
awww = true # Optional: if you use swww for wallpapers

[templates.rofi]
input_path = "~/.config/matugen/templates/matugen.rasi"
output_path = "~/.config/rofi/matugen.rasi"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/kitty-colors.conf"
post_hook = "pkill -USR1 kitty"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme && gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt-color-scheme]
input_path = "~/.config/matugen/templates/Matugen.colors"
output_path = "~/.local/share/color-schemes/Matugen.colors"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"
post_hook = "pkill -USR2 btop || true"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode-colors.json"
output_path = "~/.config/Code/User/colors-vscode.json"
post_hook = "python ~/.config/matugen/merge-vscode.py"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hyprland/hyprland-colors.conf"
post_hook = "bash ~/.config/matugen/apply-hyprland.sh"

[templates.clipse]
input_path = '~/.config/matugen/templates/clipse_theme.json'
output_path = '~/.config/clipse/custom_theme.json'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors.txt'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
