-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#111318",
  base01 = "#0c0e13",
  base02 = "#191c20",
  base03 = "#43474e",
  base04 = "#c3c6cf",
  base05 = "#e1e2e9",
  base06 = "#2e3035",
  base07 = "#37393e",

  base08 = "#cfabdb",
  base09 = "#d9bde3",
  base0A = "#bcc7db",
  base0B = "#a4c9fe",
  base0C = "#543f5e",
  base0D = "#1f4876",
  base0E = "#3c4758",
  base0F = "#9babc9",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#1f4876',
  fg = '#d3e3ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#ba87cc',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8d9199',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d9bde3',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bcc7db',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#3a608f',
})
