#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

# cursor theme
$cursor = Bibata-Modern-Ice

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,$cursor
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,$cursor

cursor {
    inactive_timeout = 3   # hides cursor after 3 seconds of inactivity
}

# font style
font = "JetBrainsMono Nerd Font"

