# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

#$wall = /home/senal/.config/hypr/pick.sh
$wall = /mnt/storage/Pictures/wallpapers/other/soldiers-night-ops-digital-art-4k-wallpaper-uhdpaper.com-90@5@l.jpg

# GENERAL
general {
  no_fade_in = true
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor =
    path = $wall
    # path = screenshot
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    # color = rgba(255, 255, 255, 1)
    color = $p1_accent_4_rgba
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 150
    font_family = AlfaSlabOne
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    # color = rgba(255, 255, 255, 1)
    color = $primary_3_rgba
    font_size = 150
    font_family = AlfaSlabOne
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    # color = rgba(255, 255, 255, 1)
    color = $p3_accent_6_rgba
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -130
    halign = center
    valign = center
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 0            # Removed outline for total transparency
    outer_color = rgba(0, 0, 0, 0)   # Fully transparent
    inner_color = rgba(0, 0, 0, 0)   # Fully transparent
    
    dots_size = 0.2 
    dots_spacing = 0.4 
    dots_center = true
    
    # This color determines the dots. 
    # Adjust the last value (0.8) to control dot opacity.
    font_color = rgba(255, 255, 255, 0.8) 
    
    fade_on_empty = true            # Set to false so dots don't vanish
    hide_input = false
    
    position = 0, -220
    halign = center
    valign = center
    zindex = 20
}