monitor=,preferred,auto,auto

source = ~/.config/matugen/themes/hyprland-colors.conf
source = hyprlang/keybinds.conf
source = hyprlang/looks.conf
source = hyprlang/input.conf
source = hyprlang/rules.conf
source = hyprlang/environment.conf

exec-once = hyprlock
exec-once = awww-daemon
exec-once = clipse -listen
