$active_border = rgb(a4c9fe)

$wall = /mnt/storage/Pictures/wallpapers/other/batman-gotham-city-4k-wallpaper-uhdpaper.com-811@2@b.jpg

# Primary Color (used for Time MM)
$primary_3_rgba = rgb(a4c9fe)

# Accent 1 (used for Time HH)
$p1_accent_4_rgba = rgb(1f4876)

# Accent 2 (used for Date)
$p3_accent_6_rgba = rgb(d9bde3)

$dot_color = rgb(bcc7db)