$active_border = rgb(8dcff1)

$wall = /mnt/storage/Pictures/wallpapers/other/river_to_castle_theme_blue.jpg

# Primary Color (used for Time MM)
$primary_3_rgba = rgb(8dcff1)

# Accent 1 (used for Time HH)
$p1_accent_4_rgba = rgb(004d66)

# Accent 2 (used for Date)
$p3_accent_6_rgba = rgb(c8c2ea)

$dot_color = rgb(8dcff1)
