$active_border = rgb(a5c9fe)

$wall = /mnt/storage/Pictures/wallpapers/other/e130ac93e37ec7e0f666ec4a8637f368.jpg

# Primary Color (used for Time MM)
$primary_3_rgba = rgb(a5c9fe)

# Accent 1 (used for Time HH)
$p1_accent_4_rgba = rgb(204876)

# Accent 2 (used for Date)
$p3_accent_6_rgba = rgb(d9bde3)

$dot_color = rgb(bcc7db)
