monitor=,preferred,auto,auto

source = ~/.config/matugen/themes/hyprland-colors.conf
source = hyprland/keybinds.conf
source = hyprland/looks.conf
source = hyprland/input.conf
source = hyprland/rules.conf
source = hyprland/environment.conf

exec-once = hyprlock
exec-once = awww-daemon
exec-once = clipse -listen
