################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto


source = ~/.config/themes/hypr/hyprland-colors.conf
source = keybinds.conf
source = looks.conf
source = input.conf
source = windowrules.conf
source = environment.conf

#################
### AUTOSTART ###
#################

exec-once = hyprlock
exec-once = awww-daemon
exec-once = ~/.config/scripts/matugen-wall.sh
exec-once = clipse -listen

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
