theme {
    color_scheme =~/.local/share/color-schemes/Matugen.colors
    icon_theme = breeze-dark
    style = Breeze
    font = JetBrains Mono
    font_size = 11
    font_fixed = JetBrains Mono
    font_fixed_size = 11
}
