general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# dim after 4 min
listener {
    timeout = 240
    on-timeout = ddcutil setvcp 10 10
    on-resume = ddcutil setvcp 10 40
}

# lock after 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# display off after 10 min
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend after 11 min
listener {
    timeout = 660                                # 11 minutes
    on-timeout = systemctl suspend                # suspend pc
}
