########## PERFORMANCE (Intel iGPU) ##########
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe        # Massive performance boost (GPU decoding)

########## SCALING & QUALITY ##########

scale=ewa_lanczossharp
dscale=mitchell
cscale=spline36
deband=yes             # Reduce "banding" in dark scenes
video-sync=display-resample
interpolation=yes      # Smoother motion

########## PLAYBACK BEHAVIOR ##########
save-position-on-quit=yes   # Auto resume next time
keep-open=yes               # Stay open when video ends
pause=no                    # Start playing immediately
loop-file=no

########## VIDEO BEHAVIOR ##########
video-unscaled=no          # Do NOT resize video
autofit-larger=0            # Never auto-scale
cursor-autohide=1000

########## AUDIO ##########
volume=100                  # Uses system volume
audio-channels=stereo

########## SUBTITLES ##########
no-sub                      # Subtitles OFF by default
sub-font-size=36
sub-border-size=2

########## SCREENSHOTS ##########
screenshot-directory=/home/senal/Pictures/mpv_screenshots/
screenshot-format=png
screenshot-template="%F_%p"
