windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# opacity

$opacity_value = opacity 0.7

windowrule = match:class codium, $opacity_value
windowrule = match:class dev.zed.Zed, $opacity_value
windowrule = match:class kitty, match:title nvim, opacity 0.8
windowrule = match:class localsend, $opacity_value
