return {
  {
    "Senal-D-A-Gunaratna/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true, -- set this to false to stop the theme from loading

      -- Path to the JSON/JSONC file generated by matugen
      palette_path = "~/.cache/matugen/nvim-colors.json",
    },
  },
  --made matugen my default colorscheme so it loads faster
  { "LazyVim/LazyVim", opts = { colorscheme = "matugen" } },

  {
    "Senal-D-A-Gunaratna/hyprfade.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      opacity = 0.7, -- normal editing opacity
      opacity_inactive = 0.75, -- opacity for inactive windows
      term_names = { "kitty" },
    },
    keys = {
      { "<leader>uo", "<cmd>HyprfadeToggle<cr>", desc = "Toggle window opacity" },
    },
  },
}
