-- Generated by Matugen

local enabled = true -- Set to false to go back to "Normal" mode

if not enabled then
  return {}
end

return {
require('base16-colorscheme').setup({
  base00 = "#121318",
  base01 = "#0d0e13",
  base02 = "#1b1b21",
  base03 = "#46464f",
  base04 = "#c6c5d0",
  base05 = "#e3e1e9",
  base06 = "#303036",
  base07 = "#38393f",

  base08 = "#dea7ce",
  base09 = "#e5bad8",
  base0A = "#c3c5dd",
  base0B = "#bac3ff",
  base0C = "#5d3c55",
  base0D = "#394379",
  base0E = "#434659",
  base0F = "#a2a6cb",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#394379',
  fg = '#dee1ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#d082b9',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#90909a',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e5bad8',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c3c5dd',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#515b92',
})
}
