return {
  {
    "Senal-D-A-Gunaratna/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true

      -- Path to the JSONC file generated by matugen
      jsonc_path = vim.fn.expand("~/.config/matugen/themes/code-colors.jsonc"),
    },
  },

  --made matugen my default colorscheme so it loads faster
  { "LazyVim/LazyVim", opts = { colorscheme = "matugen" } },
}
