-- Generated by Matugen

local enabled = true -- Set to false to go back to "Normal" mode

if not enabled then
  return {}
end

local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

return {
  {
    "RRethy/nvim-base16",
    lazy = false,
    priority = 1000,
    config = function()
      require('base16-colorscheme').setup({
        base00 = "#111318",
        base01 = "#0c0e13",
        base02 = "#191c20",
        base03 = "#43474e",
        base04 = "#c3c6cf",
        base05 = "#e1e2e9",
        base06 = "#2e3035",
        base07 = "#37393e",

        base08 = "#cfabdb",
        base09 = "#d9bde3",
        base0A = "#bcc7db",
        base0B = "#a5c9fe",
        base0C = "#543f5e",
        base0D = "#204876",
        base0E = "#3d4758",
        base0F = "#9babc9",
      })

      vim.cmd.colorscheme("base16-custom")

      -- Make selected text stand out more
      vim.api.nvim_set_hl(0, 'Visual', {
        bg = '#204876',
        fg = '#d4e3ff',
      })

      -- Make "string" text contrast better
      set_hl_multiple({ 'String', 'TSString' }, {
        fg = '#ba87cc',
      })

      -- Grey out comments
      set_hl_multiple({ 'TSComment', 'Comment' }, {
        fg = '#8d9199',
        italic = true,
      })

      set_hl_multiple({ 'TSMethod', 'Method' }, {
        fg = '#d9bde3',
      })

      set_hl_multiple({ 'TSFunction', 'Function' }, {
        fg = '#bcc7db',
      })

      set_hl_multiple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
        fg = '#3b608f',
      })
    end,
  }
}
