-- Generated by Matugen

local enabled = true -- Set to false to go back to "Normal" mode

if not enabled then
  return {}
end

local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

return {
  {
    "RRethy/nvim-base16",
    lazy = false,
    priority = 1000,
    config = function()
      require('base16-colorscheme').setup({
        base00 = "#243034",
        base01 = "#090f11",
        base02 = "#171c1e",
        base03 = "#3f484b",
        base04 = "#bfc8cb",
        base05 = "#dee3e5",
        base06 = "#2c3133",
        base07 = "#343a3c",

        base08 = "#abb4e5",
        base09 = "#bec5eb",
        base0A = "#b2cbd2",
        base0B = "#84d2e6",
        base0C = "#3e4565",
        base0D = "#004e5c",
        base0E = "#334a50",
        base0F = "#92b5bf",
      })

      -- Make selected text stand out more
      vim.api.nvim_set_hl(0, 'Visual', {
        bg = '#004e5c',
        fg = '#aaedff',
      })

      -- Make "string" text contrast better
      set_hl_multiple({ 'String', 'TSString' }, {
        fg = '#8491d9',
      })

      -- Grey out comments
      set_hl_multiple({ 'TSComment', 'Comment' }, {
        fg = '#899295',
        italic = true,
      })

      set_hl_multiple({ 'TSMethod', 'Method' }, {
        fg = '#bec5eb',
      })

      set_hl_multiple({ 'TSFunction', 'Function' }, {
        fg = '#b2cbd2',
      })

      set_hl_multiple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
        fg = '#006879',
      })
    end,
  }
}
