return {

  {
    "Senal-D-A-Gunaratna/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true, -- set this to false to stop the theme from loading

      -- Path to the JSON/JSONC file generated by matugen
      palette_path = "~/.cache/matugen/nvim-colors.json",
    },
  },
  --made matugen my default colorscheme so it loads faster
  { "LazyVim/LazyVim", opts = { colorscheme = "matugen" } },

  {
    "Senal-D-A-Gunaratna/swapson.nvim",
    dependencies = {
      "mason-org/mason.nvim",
    },
    config = function()
      require("swapson").setup({
        npm = {
          enabled = true, -- set false to skip npm->bun patching
          tool = "bun", -- the bun binary name/path
          -- Whether to also patch mason's npm version-lookup client
          -- (npm view --json) — needed on systems with NO npm
          -- installed at all, since version lookups would
          -- otherwise still shell out to npm
          patch_version_lookup = true,
        },
        pip = {
          enabled = true, -- set false to skip pip->uv patching
          tool = "uv", -- the uv binary name/path
        },
      })
    end,
  },
}
