return {

  {
    "Senal-D-A-Gunaratna/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true, -- set this to false to stop the theme from loading

      -- Path to the JSON/JSONC file generated by matugen
      palette_path = "~/.config/matugen/themes/nvim-colors.json",
    },
  },
  --made matugen my default colorscheme so it loads faster
  { "LazyVim/LazyVim", opts = { colorscheme = "matugen" } },

  {
    "Senal-D-A-Gunaratna/bunson.nvim",
    dependencies = {
      "mason-org/mason.nvim",
    },
    config = function()
      require("bunson").setup({
        patch_version_lookup = true,
      })
    end,
  },
}
