return {
  {
    "folke/which-key.nvim",
    opts = {
      spec = {
        { "<leader>a", group = "AI", icon = "󰚩" },
        { "<leader>at", desc = "Toggle AI Completion", icon = "" },
        { "<leader>k", desc = "Kitty", icon = "󰍹" },
      },
    },
  },

  {
    "supermaven-inc/supermaven-nvim",
    keys = {
      { "<leader>at", "<cmd>SupermavenToggle<cr>", desc = "Toggle AI Completion" },
    },
    config = function()
      require("supermaven-nvim").setup({
        keymaps = {
          accept_suggestion = "<Tab>", -- Hits Tab to accept the ghost text
          clear_suggestion = "<C-]>",
          accept_word = "<C-j>",
        },
      })
    end,
  },

  {
    "mbbill/undotree",
    cmd = "UndotreeToggle",
    keys = {
      { "<leader>uu", "<cmd>UndotreeToggle<cr>", desc = "Toggle UndoTree" },
    },
    config = function()
      -- Optional: Persistent undo so history survives restarts
      vim.opt.undofile = true
    end,
  },

  {
    "Senal-D-A-Gunaratna/matugen.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true,

      -- Path to the JSON/JSONC file generated by matugen
      palette_path = "~/.config/matugen/themes/nvim-colors.json",
    },
  },

  --made matugen my default colorscheme so it loads faster
  { "LazyVim/LazyVim", opts = { colorscheme = "matugen" } },

  {
    "Isrothy/neominimap.nvim",
    version = "v3.*",
    enabled = true,
    lazy = false,
    keys = {
      { "<leader>uM", "<cmd>Neominimap Toggle<cr>", desc = "Toggle Minimap" },
    },
    init = function()
      vim.g.neominimap = {
        auto_enable = false,
      }
    end,
  },

  {
    "nitinbhat972/kitty-font.nvim",
    event = "VeryLazy",
    opts = {
      font_family = "JetBrainsMono Nerd Font",
      font_size = 12,
      restore_on_exit = true,
    },
    keys = {
      {
        "<leader>k=",
        function()
          local kf = require("kitty-font")
          kf.config.font_size = (kf.config.font_size or 12) + 1
          kf.apply({ silent = true })
          vim.notify("Kitty font size: " .. kf.config.font_size)
        end,
        desc = "Kitty font size +1",
      },
      {
        "<leader>k-",
        function()
          local kf = require("kitty-font")
          kf.config.font_size = math.max(4, (kf.config.font_size or 12) - 1)
          kf.apply({ silent = true })
          vim.notify("Kitty font size: " .. kf.config.font_size)
        end,
        desc = "Kitty font size -1",
      },
      {
        "<leader>kr",
        function()
          require("kitty-font").reset()
        end,
        desc = "Kitty reset to defaults",
      },
      {
        "<leader>kf",
        function()
          require("kitty-font").pick()
        end,
        desc = "Pick Kitty font",
      },
    },
  },
}
