$active_border = rgb({{colors.primary.default.hex_stripped}})

$wall = {{image}}

# Primary Color (used for Time MM)
$primary_3_rgba = rgb({{colors.primary.default.hex_stripped}})

# Accent 1 (used for Time HH)
$p1_accent_4_rgba = rgb({{colors.primary_container.default.hex_stripped}})

# Accent 2 (used for Date)
$p3_accent_6_rgba = rgb({{colors.tertiary.default.hex_stripped}})