# matugen colors for kitty
# Standard ANSI Colors (0-7)
color0  {{colors.surface.default.hex}}             # Black/Background
color1  {{colors.error.default.hex}}               # Red
color2  {{colors.on_primary_fixed_variant.dark.hex | lighten: 10.0 }} # Green
color3  {{colors.secondary.default.hex}}           # Yellow
color4  {{colors.primary.default.hex}}             # Blue
color5  {{colors.tertiary_container.default.hex}}   # Magenta
color6  {{colors.secondary_container.default.hex | lighten: 20.0 }} # Cyan
color7  {{colors.primary.default.hex | lighten: 1.0 }}           # White/Foreground

# Bright ANSI Colors (8-15)
color8  {{colors.surface_variant.default.hex}}      # Bright Black (Gray)
color9  {{colors.error.default.hex | lighten: 10.0 }} # Bright Red
color10 {{colors.on_primary_fixed_variant.dark.hex | lighten: 20.0 }}            # Bright Green
color11 {{colors.secondary.default.hex | lighten: 10.0 }} # Bright Yellow
color12 {{colors.primary.default.hex | lighten: 5.0 }} # Bright Blue
color13 {{colors.tertiary_container.default.hex | lighten: 10.0 }} # Bright Magenta
color14 {{colors.secondary_container.default.hex | lighten: 30.0 }} # Bright Cyan
color15 {{colors.on_background.default.hex}}        # Bright White

# UI Elements
cursor               {{colors.secondary_container.default.hex | lighten: 20.0 }}
selection_background {{colors.secondary_container.default.hex | lighten: 25.0 }}
url_color            {{colors.primary_container.default.hex}}